config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#index", as: "accueil"

  get "doctors/benefits", to: 'doctors#benefit', as: "benefice"

  get "doctors/search" , to: "doctors#index", as: "recherche"

  resources :doctors


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord

    geocoded_by :address
   after_validation :geocode, :if => :address_changed?

    #  def self.search_doctor(city)
    #   where("city = ? || address = ?", city, city)
    # end

    scope :search_doctor, ->(city) { where("address = ?", city) }

    has_many :appointments

end

# where("mot_cle = ? || address = ?", params[:mot_cle], params[:lieu] )

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

    # before_action :set_doctor, only: [:show, :edit, :update, :destroy]

	def benefit

	end

  def index
    if params[:city].blank?
        @doctors = Doctor.all
        # @hash = Gmaps4rails.build_markers(@doctors) do |doctor, marker|
        # marker.lat doctor.latitude
        # marker.lng doctor.longitude
    else
        @doctors = Doctor.search_doctor(params[:city])
        # @hash = Gmaps4rails.build_markers(@doctors) do |doctor, marker|
        # marker.lat doctor.latitude
        # marker.lng doctor.longitude
    end
  end

  def show

  end

  def new
    # @doctor = Doctor.new
  end

  def create
    # @doctor = Doctor.new(doctor_params)
    # if @doctor.save
    #   flash[:success] = "Doctor added!"
    #   redirect_to root_path
    # else
    #   render :nex
    # end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def set_doctor
  	@doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :second_name, :phone_number, :address)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/doctors/benefit.html.erb
<div class="jumbotron jumbotron-fluid py-5 mini_banner mb-0 bg-info">
  <div class="container text-center">
  	<div class="row">
			<div class="col-md-6">
				<h2 class="font-weight-bold text-white mb-3">Développez votre patientèle avec la prise de rendez-vous en ligne.</h2>
    		<p class=" text-white"><span class="sr-only">Prise de rendez-vous en ligne, SMS de rappel, communication patient en 1 clic.</span>Grâce à <span class="font-weight-bold">Dototché</span> optimisez dès maintenant la gestion de vos rendez-vous et développer votre patientèle.</p>
			</div>
			<div class="col-md-5 offset-md-1">
				<div class="card">
					<div class="card-body">
						<h4>Voulez-vous en savoir plus ?</h4>
						<p><small>Remplisser ce formulaire</small></p>

					</div>
				</div>
			</div>
  	</div>
  </div>
</div>

<section class="container-fluid py-5">
	<div class="container">
		<div class="row">
			<div class="col-12 text-center mb-4">
				<h2>Pourquoi les médecins utilisent-ils <span class="font-weight-bold">Dototché</span> ?</h2>
			</div>
			<div class="col-md-3 text-center">
					<i class="fa fa-clock-o text-primary fa-5x mb-3" aria-hidden="true"></i>
					<p class="h5">Développer la présence en ligne de votre cabinet médical</p>
			</div>
			<div class="col-md-3 text-center">
				<i class="fa fa-thumbs-o-up text-primary fa-5x mb-3" aria-hidden="true"></i>
					<p class="h5">Améliorer votre réputation et celui de votre cabinet médical</p>
			</div>
			<div class="col-md-3 text-center">
					<i class="fa fa-stethoscope text-primary fa-5x mb-3" aria-hidden="true"></i>
					<p class="h5">Permettrer à vos patientèles de prendre RDV sans avoir à vous appeler</p>
			</div>
			<div class="col-md-3 text-center">
				<i class="fa fa-line-chart text-primary fa-5x mb-3" aria-hidden="true"></i>
				<p class="h5">Apportez un service nouveau pour vos patients</p>
			</div>
			<div class="col-12 mt-4">
				<p class="text-center mb-0"><%= link_to "Inscrivez-vous maintenant", accueil_path, class: "btn btn-primary btn-lg"  %></p>
			</div>
		</div>
	</div>
</section>

<section class="container-fluid sr-only">
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1 text-center mb-4">
          <h2>Ils nous font confiance</h2>
      </div>
		</div>
	</div>
</section>

<section class="container-fluid bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1 text-center text-dark mb-4">
                <h2>Ils parlent de nous</h2>
                <p class="lead sr-only">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, quia?</p>
            </div>
            <div class="col-12">
                <div class="row ils_parlent_de_nous">
                    <div class="col-12 col-md-4 d-flex justify-content-center mx-1">
												<%= image_tag "logo_ortb.png" %>
                    </div>
                    <div class="col-12 col-md-4 d-flex justify-content-center mx-1">
												<%= image_tag "logo.png" %>
                    </div>
                    <div class="col-12 col-md-4 d-flex justify-content-center mx-1">
												<%= image_tag "65px-Rfi_logo.svg.png" %>
                    </div>
                    <div class="col-12 col-md-4 d-flex justify-content-center mx-1">
												<%= image_tag "logo_ortb.png" %>
                    </div>
                    <div class="col-12 col-md-4 d-flex justify-content-center mx-1">
												<%= image_tag "logo.png" %>
                    </div>
                    <div class="col-12 col-md-4 d-flex justify-content-center mx-1">
												<%= image_tag "65px-Rfi_logo.svg.png" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<% content_for :slick_ils_parlent_de_nous do %>
	<script>
	    $(document).ready(function(){
	       $('.ils_parlent_de_nous').slick({
					  infinite: true,
					  slidesToShow: 3,
					  slidesToScroll: 1,

					  autoplay: true,

					   dots: true,
  speed: 300,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]

					});
	    });
	</script>
<% end %>

app/views/doctors/index.html.erb
<% provide :page_title, "Resultat de recherche" %>


<script src="//maps.google.com/maps/api/js?key=AIzaSyCtgANIAB9yJJCjMbqKedo_EO-09kCfVrM"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js'></script> <!-- only if you need custom infoboxes -->



<div class="jumbotron jumbotron-fluid py-5 mini_banner mb-0 bg-info">
  <div class="container">
    <div class="row">
			<div class="col-md-5">
				<p class="lead text-white mb-0">Affichage de 10 résultats</p>
			</div>
			<div class="col-md-7">
          <%= form_with scope: :doctor, url: recherche_path, method: :get, local: true do |f|  %>
              <div class="row">
                  <div class="col-md-10 px-0">
                      <div class="form-group">
                           <%= f.text_field :mot_cle, class: "form-control supri-bordu", placeholder: "Entrer le nom d'un médecin ou clinique" %>
                      </div>
                  </div>
                  <div class="col-md-2 px-0">
                      <div class="form-group">
                          <%= f.submit "Rechercher", class: "btn btn-primary  btn btn-block supri-bordu" %>
                      </div>
                  </div>
              </div>
          <% end %>
			</div>
		</div>
  </div>
</div>

<section class="container-fluid bg-light py-3">
	<div class="container">
		<p class="mb-1">Type</p>
		<ul class="nav nav-pills small">
		  <li class="nav-item">
		    <a class="nav-link active" href="#">Active</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" href="#">Link</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" href="#">Link</a>
		  </li>
		</ul>
	</div>

	<hr>

	<div class="container py-4">
		<div class="row">
			<div class="col-md-7">
				<div class="card mb-3">
					<div class="card-body">
						<div class="row">
							<div class="col-md-3 text-center">
								<a href=""><%= image_tag "boy-2027768_640.png", class: "img-fluid rounded-cicle w-75", style: "border-radius: 50%"  %></a>
							</div>
							<div class="col-md-9">
								<h5 class="font-weight-bold mb-0">Dr. Gaston CAKPO</h5>
								<small>PEDIATRICIAN</small>
								<p class="mt-3">L'adresse du médecin a cette endroit</p>
								<p>ratting ici</p>

							</div>
						</div>
					</div>
					<hr class="m-0">
					<div class="card-body">
						<div class="row">
							<div class="col-md-3">

							</div>
							<div class="col-md-9 d-flex justify-content-between">
								<p class="mb-0"><a href="">Voir sur la carte</a></p>
								<p class="mb-0"><a href="" class="btn btn-primary btn-sm">Prendre un RDV</a></p>
							</div>
						</div>
					</div>
				</div>


			</div>
			<div class="col-md-5 ">
				<div class="w-100 sticky-top" id="map">
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Pour gmap4rails -->
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="fr">
  <head>

        <link href="https://fonts.googleapis.com/css?family=Pacifico|Roboto:400,500,700,900" rel="stylesheet">

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <meta name="description" content="Application de prise de rendez-vous en ligne chez un médecin">
        <meta name="author" content="Francel AMAMOO">

        <title>Dototché - <%= content_for?(:page_title) ? yield(:page_title) : "Pas de title" %></title>

        <%= favicon_link_tag "stethoscope-icon-2316460_1280.png" %>

        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css", media: "all" %>

        <!-- Add the slick-theme.css if you want default styling -->
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css"/>
        <!-- Add the slick-theme.css if you want default styling -->
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css"/>

  </head>
  <body class="Controller : <%= controller.controller_name  %>, Action : <%= controller.action_name  %>">

        <% flash.each do |name, message| %>
            <%= content_tag :div, message, class: name %>
        <% end %>

        <%= render "shareds/navbar" %>

        <main>

            <%= yield %>

        </main>

        <%= render "shareds/mobile_apps" %>

        <%= render "shareds/footer" %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js"></script>

        <% if current_page?(accueil_path) %>

            <script>
            $(document).ready(function(){
                $('.center').slick({
                dots: true,
                autoplay: true,
                centerMode: true,
                centerPadding: '60px',
                slidesToShow: 3,
                responsive: [
                {
                breakpoint: 768,
                settings: {
                arrows: false,
                centerMode: true,
                centerPadding: '40px',
                slidesToShow: 3
                }
                },
                {
                breakpoint: 480,
                settings: {
                arrows: false,
                centerMode: true,
                centerPadding: '40px',
                slidesToShow: 1
                }
                }
                ]
                });
            });
        </script>

        <% elsif current_page?(benefice_path) %>
            <%= yield :slick_ils_parlent_de_nous %>
        <% else %>

        <% end %>

    </body>
</html>

app/views/shareds/_autre.html.erb
<%= form_with url: recherche_path, method: :get, local: true, class: "px-2", role: "search" do |f|  %>
                    <div class="row">
                        <div class="col-md-5 px-0">
                            <div class="form-group">
                                 <%= f.text_field :mot_cle, class: "form-control form-control-lg supri-bordu", placeholder: "Nom d'un médecin, clinique ou spécialité" %>
                            </div>
                        </div>
                        <div class="col-md-5 px-0">
                            <div class="form-group">
                               <%= f.text_field :lieu, class: "form-control form-control-lg supri-bordu", placeholder: "Nom de votre ville ou quartier" %>
                            </div>
                        </div>
                        <div class="col-md-2 px-0">
                            <div class="form-group">
                                <%= f.submit "Rechercher", class: "btn btn-primary btn-lg btn btn-block supri-bordu" %>
                            </div>
                        </div>
                    </div>
                <% end %>


                
<!-- <div class="container sr-only">
	<form class="form-signin">
		<h2 class="form-signin-heading">Please sign in</h2>
		<label for="inputEmail" class="sr-only">Email address</label>
		<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
		<label for="inputPassword" class="sr-only">Password</label>
		<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
		<div class="checkbox">
			<label>
				<input type="checkbox" value="remember-me"> Remember me
			</label>
		</div>
		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	</form>
</div>


<section class="container-fluid" style="background-color: #3799ff;">
	<div class="container-fluid">
		<div class="row py-3">
			<div class="col-12 text-center">
				<h2 class="text-light">Déposer une annonce</h2>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container">
		<div class="row py-5">
			<div class="col-lg-8 offset-lg-2 ">
				<p>
					<span class="font-weight-bold">Info :</span> Les champs précédé du signe ( * ) doivent être renseigné ! </p>

				<%= simple_form_for :ad do |f| %>
					<div class="card mb-4">
						<div class="card-header bg-primary">
							<p class="text-light font-weight-bold mb-0">Votre annonce</p>
						</div>
						<div class="card-body">

							<%= f.association :category, label: "Catégorie", prompt: "--- Sélectionner une catégorie ---" %>

								<%= f.association :ad_type, as: :radio_buttons, label: "Type d'annonce" %>

									<%= f.association :seller_type, as: :radio_buttons, label: "Vous êtes un" %>

										<%= f.input :title, label: "Titre de l'annonce" %>

											<%= f.input :description, as: :text, label: "Description de l'annonce", input_html: { rows: 10 }  %>
												<%= f.input :price, as: :integer, label: "Prix"  %>

													<p>
														<small>
															<strong>Photos : </strong>Une annonce avec photo est 8 fois plus consultée qu'une annonce sans photo.</small>
													</p>

													<%= f.input :photo_one, as: :file, wrapper: :horizontal_file_input, label: "Photo 1" %>
														<%= f.input :photo_two, as: :file, wrapper: :horizontal_file_input, label: "Photo 2" %>
															<%= f.input :photo_three, as: :file, wrapper: :horizontal_file_input, label: "Photo 3" %>
						</div>
					</div>

					<div class="card mb-4">
						<div class="card-header bg-primary">
							<p class="text-light font-weight-bold mb-0">Localisation</p>
						</div>
						<div class="card-body">
							<%= f.input :ad_adress, label: "Adresse", placeholder: "Saisissez le lieu ou se trouve l'objet" %>
						</div>
					</div>

					<div class="card mb-4">
						<div class="card-header bg-primary">
							<p class="text-light font-weight-bold mb-0">Vos informations</p>
						</div>
						<div class="card-body">
							<%= f.input :seller_name, label: "Nom"  %>

								<%= f.input :seller_email, as: :email, placeholder: 'utilisateur@domaine.com', label: "Email"  %>

									<%= f.input :seller_phone_number, as: :tel, label: "Numéro de téléphone", input_html: { maxlength: 8 }  %>
						</div>
					</div>

					<%= f.button :submit, "Valider l'annonce", class: "btn btn-primary" %>
						<% end %>
			</div>
		</div>
	</div>
</section> -->

app/views/shareds/_footer.html.erb
<footer class="container-fluid">
	<div class="container">
		<div class="row pt-5 pb-3">
			<div class="col-md-3 my-3 my-md-0">
				<h5 class="mb-3 text-uppercase font-weight-bold"><i class="fa fa-plus-square fa-lg" aria-hidden="true""></i> Dototché</h5>
				<p></p>
			</div>
			<div class="col-md-3 my-3 my-md-0">
				<h5 class="mb-3">A propos</h5>
				<ul class="nav flex-column">
					<li class="nav-item">
						<%= link_to 'Qui sommes-nous', page_path('about'), class: "nav-link pl-0 py-1 text-dark" %>
					</li>
					<li class="nav-item">
						<%= link_to 'Contacter-nous', page_path('about'), class: "nav-link pl-0 py-1 text-dark" %>
					</li>
					<li class="nav-item">
						<%= link_to "Carrières", accueil_path, class: "nav-link pl-0 py-1 text-dark" %>
					</li>
				</ul>
			</div>
			<div class="col-md-3 my-3 my-md-0">
				<h5 class="mb-3">Liens utiles</h5>
				<ul class="nav flex-column">
					<li class="nav-item">
						<%= link_to "Rechercher par ville", accueil_path, class: "nav-link pl-0 py-1 text-dark" %>
					</li>
					<li class="nav-item">
						<%= link_to "Rechercher par spécialité", accueil_path, class: "nav-link pl-0 py-1 text-dark" %>
					</li>
					<li class="nav-item">
						<%= link_to "Blog", accueil_path, class: "nav-link pl-0 py-1 text-dark" %>
					</li>
					<li class="nav-item">
						<%= link_to "FAQ", accueil_path, class: "nav-link pl-0 py-1 text-dark" %>
					</li>
				</ul>
			</div>
			<div class="col-md-3 my-3 my-md-0">
				<h5 class="mb-3">Contact</h5>
				<address>
					<ul class="nav flex-column">
						<li class="nav-item">
							<a href="" class="nav-link pl-0 py-1 text-dark">
								<i class="fa fa-phone mr-1" aria-hidden="true"></i>
								<span>(229) 62 20 03 90</span>
							</a>
						</li>
						<li class="nav-item">
							<%= mail_to "francel.webdev@gmail.com", subject: "Demande d'information !", class: "nav-link pl-0 py-1 text-dark" do %>
								<i class="fa fa-envelope-o mr-1" aria-hidden="true"></i>
								<span>francel.webdev@gmail.com</span>
							<% end %>
						</li>
					</ul>
				</address>

				<h5 class="mb-3 my-3 my-md-0">Suivez-nous sur</h5>
				<ul class="nav">
					<li class="nav-item">
						<%= link_to "http://facebook.com", class: "nav-link pl-0 text-dark" do %>
							<i class="fa fa-facebook fa-lg mr-1" aria-hidden="true"></i>
						<% end %>
					</li>
					<li class="nav-item">
						<%= link_to "http://facebook.com", class: "nav-link pl-0 text-dark" do %>
							<i class="fa fa-twitter fa-lg mr-1" aria-hidden="true"></i>
						<% end %>
					</li>
				</ul>
			</div>
			<div class="col-12">
				<hr>
			</div>
			<div class="col-md-6">
				<ul class="nav">
					<li class="nav-item">
						<%= link_to page_path('contact'), class: "nav-link pl-0 text-dark" do %>
							<small>Conditions générales d'utilisation</small>
						<% end %>
					</li>
					<li class="nav-item">
						<%= link_to page_path('contact'), class: "nav-link pl-0 text-dark" do %>
							<small>Politique de confidentialité</small>
							<% end %>
					</li>
				</ul>
			</div>
			<div class="col-md-6 text-center text-md-right">
				<p class="text-dark text-md-right mt-2 mb-0"><small>&copy; 2017 - <%= Time.now.year %> Dototché. Tous droit réservé.</small></p>
			</div>
		</div>
	</div>
</footer>

app/views/shareds/_jumbotron.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron jumbotron-fluid d-flex align-items-center mb-0 jumbotron-welcomes">
		<div class="container text-center">
				<h1 class="text-white">Finies les attentes interminables dans les hôpitaux</h1>
				<p class="lead text-white mb-4">Trouvez un médecin près de chez vous et prenez RDV en quelque clic !</p>
			 <div class="row">
						<div class="col-12">
								<%= form_with url: recherche_path, method: :get, local: true do |form|  %>
									<div class="row px-1">
											<!-- <div class="col-md-5 px-0">
												<%= form.text_field :mot_cle, class: "form-control form-control-lg supri-bordu", placeholder: "Nom d'un médecin, clinique ou spécialité" %>
											</div>
 -->									<div class="col-md-6 offset-md-2 px-0" style="box-shadow: 0 5px 30px rgba(156, 160, 171, 0.25) !important;">
												<%= form.text_field :city, required: true, placeholder: "Nom de votre ville ou quartier. Ex: Agla, Zogbo, Fifadji", class: 'form-control form-control-lg supri-bordu' %>
											</div>
											<div class="col-md-2 px-0" style="box-shadow: 0 5px 30px rgba(156, 160, 171, 0.25) !important;">
												<%= form.submit "Rechercher", name: nil, class: 'btn btn-primary btn-lg btn btn-block supri-bordu' %>
											</div>
									</div>
								<% end %>
						</div>

						<div class="col-12 text-center text-white sr-only">
							<p class="h1">Ou</p>
						</div>

						<div class="col-12 d-flex justify-content-center align-items-center sr-only">
								<ul class="nav nav-pills">
									<li class="nav-item">
										<a class="nav-link active" href="#">A proximité de moi</a>
									</li>
								</ul>
						</div>

			 </div>
		</div>
</div>

app/views/shareds/_mobile_apps.html.erb
<section class="container-fluid mobile_app py-5 bg-info">
	<div class="container">
		<div class="row">
			<div class="col-md-5 text-center mb-4 mb-md-0">
				<%= image_tag "app_img.svg", alt: "App Mobile Dototché", class: "w-100" %>
			</div>
			<div class="col-md-7 text-white text-center text-md-left">
				<small>Apps</small>
				<h3 class="font-weight-bold">Télécharger gratuitement l'apps <span style="color: #FFF02A;">Dototché</span>.</h3>
				<p class="lead">L'apps <span style="color: #FFF02A;">Dototché</span> est disponible sur :</p>
				<br>
				<p>
					<%= image_tag "apple_app.png" %>
					<%= image_tag "google_play_app.png" %>
				</p>
			</div>
		</div>
	</div>
</section>

app/views/shareds/_navbar.html.erb
<!-- navbar-light bg-light -->
<nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top" style="box-shadow: rgba(0, 0, 0, 0.4) 0px 2px 4px 0px, rgba(0, 0, 0, 0.2) 0px 2px 20px 0px;">
	<!-- " style="box-shadow: 0 2px 10px rgba(0,0,0,.3); -->
	<div class="container">
		<%= link_to accueil_path, class: "navbar-brand font-weight-bold text-uppercase" do %>
			<i class="fa fa-plus-square fa-lg d-inline-block align-center" aria-hidden="true"></i> Dototché
		<% end %>
		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse mt-3 mt-md-0" id="navbarsExample07">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item active sr-only">
					<a class="nav-link px-3" href="<%= accueil_path %>">Accueil <span class="sr-only">(current)</span></a>
				</li>

				<% if current_page?(accueil_path)  %>
					<li class="nav-item">
						<%= link_to "Vous êtes medécin ?", benefice_path, class: "nav-link px-3 btn btn-primary text-white"  %>
					</li>
				<% elsif current_page?(benefice_path)  %>
					<li class="nav-item">
						<a class="nav-link px-3" href="<%= accueil_path %>">Accueil <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<%= link_to "Bénefices", benefice_path, class: "nav-link px-3 active"  %>
					</li>
				<% end %>
				<li class="nav-item">
					<%= link_to "Connexion", accueil_path, class: "ml-2 nav-link px-3" %>
				</li>
			</ul>
		</div>
	</div>
</nav>

app/views/shareds/_search_form.html.erb
<%= simple_form_for :search, url: , method: :get do |f| %>
  <div class="row px-1">
      <div class="col-md-5 px-0">
        <%= f.input :mot_cle, label: false, placeholder: "Nom d'un médecin, clinique ou spécialité", input_html: { class: 'form-control form-control-lg supri-bordu' } %>
      </div>
      <div class="col-md-6 offset-md-2 px-0">
        <%= f.input :lieu, label: false, required: true, placeholder: "Nom de votre ville ou quartier", input_html: { class: 'form-control form-control-lg supri-bordu' } %>
      </div>
      <div class="col-md-2 px-0">
        <%= f.button :submit, "Rechercher", name: nil,  class: 'btn btn-primary btn-lg btn btn-block supri-bordu' %>
      </div>
  </div>
<% end %>